name: SAST UNA-CHAT JOSUE

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # Job de Testing y SAST (análisis estático de seguridad)
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: List installed packages
        run: npm list

      - name: Run tests
        run: npm test

  # Job de análisis estático con CodeQL
  codeql:
    name: Analyze code with CodeQL
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Establecer CodeQL
      - name: Set up CodeQL
        uses: github/codeql-action/setup@v2

      # Análisis de seguridad con CodeQL
      - name: Run CodeQL Analysis
        uses: github/codeql-action/analyze@v2
        with:
          category: security

      # Guardar los resultados del análisis
      - name: Save CodeQL results
        run: |
          mkdir -p $GITHUB_WORKSPACE/codeql-results
          cp -r $CODEQL_DB_PATH/* $GITHUB_WORKSPACE/codeql-results/
