name: SAST UNA-CHAT JOSUE

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # Job de Testing
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: List installed packages
        run: npm list

      - name: Run tests
        run: npm test

  # Job 5: CodeQL (SAST - Static Code Analysis)
  codeql:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      security-events: write
    strategy:
      matrix:
        language: [ 'javascript' ]  # Aquí indicamos el lenguaje que queremos analizar (puedes agregar más si lo necesitas)
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: ${{ matrix.language }}

      - name: Autobuild
        uses: github/codeql-action/autobuild@v2
        # La acción 'autobuild' intenta construir el código de manera automática para que el análisis funcione correctamente

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
        # Esta acción realiza el análisis estático en busca de vulnerabilidades y otros problemas de seguridad

