name: UNA-CHAT JOSUE

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # Job de construcción e instalación de dependencias
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

  # Job de Linting para análisis de convenciones de código
  lint:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Run ESLint
        run: npm run lint --if-present

  # Job de Testing
  test:
    runs-on: ubuntu-latest
    needs: [build, lint]
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: List installed packages
        run: npm list

      - name: Run tests
        run: npm test

  # Job de escaneo de imágenes de Docker
  docker-scan:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t josue96/chat-una-app:latest .

      # Paso para actualizar la base de datos de Trivy (solo una vez)
      - name: Update Trivy DB
        run: |
          trivy --download-db-only

      - name: Scan Docker image for vulnerabilities
        run: |
          trivy image --exit-code 1 --severity HIGH,CRITICAL --skip-update josue96/chat-una-app:latest

      - name: Push Docker image if scan passes
        if: success()
        run: docker push josue96/chat-una-app:latest

  # Job de despliegue a ambiente de staging
  deploy-staging:
    runs-on: ubuntu-latest
    needs: docker-scan
    steps:
      - name: Deploy to Staging Environment
        env:
          STAGING_SERVER: ${{ secrets.STAGING_SERVER }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
          ssh -o StrictHostKeyChecking=no $STAGING_SERVER 'docker pull josue96/chat-una-app:latest && docker-compose up -d'

  # Job de monitoreo de seguridad con Nuclei en staging
  nuclei-scan:
    runs-on: ubuntu-latest
    needs: deploy-staging
    steps:
      - name: Run Nuclei Security Scans
        uses: projectdiscovery/nuclei-action@v1
        with:
          url: ${{ secrets.STAGING_URL }}
