# Flujo de trabajo para UNA-CHAT JOSUE con SAST, Linting, escaneo de imágenes de contenedor y despliegue a staging

name: UNA-CHAT JOSUE

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # Job de construcción e instalación de dependencias
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

  # Job de Linting para análisis de convenciones de código
  lint:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Run ESLint
        run: npm run lint --if-present

  # Job de SAST (Análisis de seguridad estática) con Semgrep
odeql:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      security-events: write
    strategy:
      matrix:
        language: [ 'javascript' ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: ${{ matrix.language }}

      - name: Autobuild
        uses: github/codeql-action/autobuild@v2

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2


  # Job de Testing
  test:
    runs-on: ubuntu-latest
    needs: [build, lint, sast]
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: List installed packages
        run: npm list

      - name: Run tests
        run: npm test

  # Job de escaneo de imágenes de Docker
  docker-scan:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t josue96/chat-una-app:latest .

      - name: Scan Docker image for vulnerabilities
        uses: aquasecurity/trivy-action@v0.6.1
        with:
          image-ref: josue96/chat-una-app:latest

      - name: Push Docker image if scan passes
        if: success()
        run: docker push josue96/chat-una-app:latest

  # Job de despliegue a ambiente de staging
  deploy-staging:
    runs-on: ubuntu-latest
    needs: docker-scan
    steps:
      - name: Deploy to Staging Environment
        env:
          STAGING_SERVER: ${{ secrets.STAGING_SERVER }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
          ssh -o StrictHostKeyChecking=no $STAGING_SERVER 'docker pull josue96/chat-una-app:latest && docker-compose up -d'

  # Job de monitoreo de seguridad con Nuclei en staging
  nuclei-scan:
    runs-on: ubuntu-latest
    needs: deploy-staging
    steps:
      - name: Run Nuclei Security Scans
        uses: projectdiscovery/nuclei-action@v1
        with:
          url: ${{ secrets.STAGING_URL }}
